Added hex encoding and specs to test against the PHP reference implementation
mguymon/paseto.rb pull request #11
Opened 2020-03-12 12:26 UTC by shaicoleman

2020-03-12 13:16 UTC, mguymon requested changes

2020-03-12 13:16 UTC, mguymon commented on lib/paseto/local.rb
> +          Paseto.encode_hex(@key)
Is it possible to add a simple test for the encode_hex?

2020-03-12 15:02 UTC, mguymon commented
I have a love / hate relationship with rubocop

2020-03-12 15:07 UTC, mguymon approved these changes
Looks good, ill push it out as 0.4.1

2020-03-13 09:28 UTC, shaicoleman commented
I've added a fix, so `Paseto::V2::Public::SecretKey.generate.encode_hex` works

2020-03-14 01:40 UTC, merged

2020-03-14 01:43 UTC, mguymon commented
released in https://rubygems.org/gems/paseto/versions/0.4.1